# config for the database client
mysql_user: root
mysql_password:
mysql_cert:
mysql_key:
mysql_rootCA:
mysql_defaults_file: config/my_development.cnf

# config for the rest client
rest_api: http://127.0.0.1:3000/api/v1/
rest_cert:
rest_key:

# general config
log_dir: /tmp/shift/
pt_osc_path: pt-online-schema-change
pending_drops_db:
log_sync_interval: 10
state_sync_interval: 10

# optionally override the host/port/db to run an OSC on
host_override:
port_override:
database_override:
